import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import { jwtDecode } from "jwt-decode";

const AuthContext = createContext(null);

function parseUserFromToken(token) {
  if (!token) return null;

  const decoded = jwtDecode(token);

  const username =
    decoded.unique_name ||
    decoded["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"] ||
    decoded.name ||
    decoded.sub ||
    "User";

  const role =
    decoded.role ||
    decoded["http://schemas.microsoft.com/ws/2008/06/identity/claims/role"] ||
    "User";

  const id =
    decoded.sid ||
    decoded["http://schemas.xmlsoap.org/ws/2005/05/identity/claims/sid"] ||
    null;

  return { id, username, role };
}

export function AuthProvider({ children }) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState('');
  // added to track user roles from the JWT
  const [roles, setRoles] = useState([]);
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  const isLoggedIn = !!user;

  useEffect(() => {
    const token = localStorage.getItem("accessToken");

    if (token) {
      try {
        const decoded = jwtDecode(accessToken);
        // tokens generated by the backend map ClaimTypes.Name to unique_name
        // jwt-decode will expose the raw claim keys (e.g. "unique_name" or
        // the full URI).  Try several possibilities before falling back.
        const nameClaim = decoded.unique_name 
                          || decoded['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
                          || decoded.name
                          || 'User';
        setUsername(nameClaim);
        setIsLoggedIn(true);
        // extract role(s) from the token as well
        const rawRole = decoded.role 
                      || decoded.roles 
                      || decoded['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']
                      || [];
        let roleArray = [];
        if (typeof rawRole === 'string') {
          // some tokens send a single role string or comma separated
          roleArray = rawRole.includes(',') ? rawRole.split(',').map(r=>r.trim()) : [rawRole];
        } else if (Array.isArray(rawRole)) {
          roleArray = rawRole;
        }
        setRoles(roleArray);
        setUser(parseUserFromToken(token));
      } catch (err) {
        console.error("Invalid token:", err);
        localStorage.removeItem("accessToken");
        setUser(null);
      } finally {
        setLoading(false);
      }
      return;
    }

    setLoading(false);
  }, []);

  const login = (token) => {
    try {
      const decoded = jwtDecode(token);
      const nameClaim = decoded.unique_name 
                        || decoded['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
                        || decoded.name
                        || 'User';
      setUsername(nameClaim);
      setIsLoggedIn(true);
      // also decode roles when logging in directly
      const rawRole = decoded.role 
                    || decoded.roles 
                    || decoded['http://schemas.microsoft.com/ws/2008/06/identity/claims/role']
                    || [];
      let roleArray = [];
      if (typeof rawRole === 'string') {
        roleArray = rawRole.includes(',') ? rawRole.split(',').map(r=>r.trim()) : [rawRole];
      } else if (Array.isArray(rawRole)) {
        roleArray = rawRole;
      }
      setRoles(roleArray);
      localStorage.setItem('accessToken', token);
    } catch (err) {
      console.error('Invalid token:', err);
      throw err;
    }
    const parsed = parseUserFromToken(token);
    localStorage.setItem("accessToken", token);
    setUser(parsed);
    return parsed;  
  };

  const logout = async () => {
    try {
      await fetch('https://localhost:7261/api/auth/logout', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${localStorage.getItem("accessToken")}`,
        },
        credentials: "include",
      });
    } catch (err) {
      console.error("Logout error:", err);
    } finally {
      localStorage.removeItem("accessToken");
      setUser(null);
    }
  };

  const refreshAccessToken = async () => {
    try {
      const response = await fetch('https://localhost:7261/api/auth/refresh-token', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', 
      });

      if (response.ok) {
        const data = await response.json();
        // Use your existing login logic to save the new token
        login(data.accessToken); 
        return data.accessToken;
      } else {
        logout();
      }
    } catch (err) {
      console.error("Failed to refresh token", err);
      logout();
    }
  };

  return (
    <AuthContext.Provider value={{ isLoggedIn, username, roles, loading, login, logout, refreshAccessToken }}>
      {children}
    </AuthContext.Provider>
  const value = useMemo(
    () => ({
      user,
      isLoggedIn,
      loading,
      login,
      logout,
    }),
    [user, isLoggedIn, loading]
  );

  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

export function useAuth() {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error("useAuth must be used within AuthProvider");
  return ctx;
}