import React, { createContext, useContext, useState, useEffect } from 'react';
import { jwtDecode } from 'jwt-decode';

const AuthContext = createContext();

export function AuthProvider({ children }) {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [username, setUsername] = useState('');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const accessToken = localStorage.getItem('accessToken');
    if (accessToken) {
      try {
        const decoded = jwtDecode(accessToken);
        // tokens generated by the backend map ClaimTypes.Name to unique_name
        // jwt-decode will expose the raw claim keys (e.g. "unique_name" or
        // the full URI).  Try several possibilities before falling back.
        const nameClaim = decoded.unique_name 
                          || decoded['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
                          || decoded.name
                          || 'User';
        setUsername(nameClaim);
        setIsLoggedIn(true);
      } catch (err) {
        console.error('Invalid token:', err);
        localStorage.removeItem('accessToken');
      }
    } else {
      refreshAccessToken(); 
    }
    setLoading(false);
  }, []);

  const login = (token) => {
    try {
      const decoded = jwtDecode(token);
      const nameClaim = decoded.unique_name 
                        || decoded['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name']
                        || decoded.name
                        || 'User';
      setUsername(nameClaim);
      setIsLoggedIn(true);
      localStorage.setItem('accessToken', token);
    } catch (err) {
      console.error('Invalid token:', err);
      throw err;
    }
  };

  const logout = async () => {
    try {
      await fetch('https://localhost:7261/api/auth/logout', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${localStorage.getItem('accessToken')}`,
        },
        credentials: 'include',
      });
    } catch (err) {
      console.error('Logout error:', err);
    } finally {
      localStorage.removeItem('accessToken');
      setIsLoggedIn(false);
      setUsername('');
    }
  };

  const refreshAccessToken = async () => {
    try {
      const response = await fetch('https://localhost:7261/api/auth/refresh-token', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include', // CRITICAL: This sends the HttpOnly cookie!
      });

      if (response.ok) {
        const data = await response.json();
        // Use your existing login logic to save the new token
        login(data.accessToken); 
        return data.accessToken;
      } else {
        // If the refresh token is expired too, log them out
        logout();
      }
    } catch (err) {
      console.error("Failed to refresh token", err);
      logout();
    }
  };

  return (
    <AuthContext.Provider value={{ isLoggedIn, username, loading, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export function useAuth() {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within AuthProvider');
  }
  return context;
}
