apiVersion: v1
kind: Secret
metadata:
  name: personalpodcast-secrets
  namespace: personalpodcast
type: Opaque
stringData:
  DB_CONNECTION: "" # constring tdatabazes
  # ndiscord
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""	